/**
 * generated by Xtext 2.9.1
 */
package de.larsschuetze.storyboard.dsl.impl;

import de.larsschuetze.storyboard.dsl.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class DslFactoryImpl extends EFactoryImpl implements DslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static DslFactory init()
  {
    try
    {
      DslFactory theDslFactory = (DslFactory)EPackage.Registry.INSTANCE.getEFactory(DslPackage.eNS_URI);
      if (theDslFactory != null)
      {
        return theDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new DslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case DslPackage.STORYBOARD: return createStoryboard();
      case DslPackage.ABSTRACT_ELEMENT: return createAbstractElement();
      case DslPackage.NODE: return createNode();
      case DslPackage.CONTROL_NODE: return createControlNode();
      case DslPackage.START_NODE: return createStartNode();
      case DslPackage.EVENT: return createEvent();
      case DslPackage.TRANSITION: return createTransition();
      case DslPackage.STORY_PATTERN_NODE: return createStoryPatternNode();
      case DslPackage.ROLE_NODE: return createRoleNode();
      case DslPackage.REWRITE_ROLE_NODE: return createRewriteRoleNode();
      case DslPackage.REMOVE_ROLE_NODE: return createRemoveRoleNode();
      case DslPackage.RENEW_ROLE_NODE: return createRenewRoleNode();
      case DslPackage.ADD_ROLE_NODE: return createAddRoleNode();
      case DslPackage.CONDITION_ROLE_NODE: return createConditionRoleNode();
      case DslPackage.PROHIBITED_ROLE_NODE: return createProhibitedRoleNode();
      case DslPackage.PLAY_ROLE_NODE: return createPlayRoleNode();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Storyboard createStoryboard()
  {
    StoryboardImpl storyboard = new StoryboardImpl();
    return storyboard;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AbstractElement createAbstractElement()
  {
    AbstractElementImpl abstractElement = new AbstractElementImpl();
    return abstractElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Node createNode()
  {
    NodeImpl node = new NodeImpl();
    return node;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ControlNode createControlNode()
  {
    ControlNodeImpl controlNode = new ControlNodeImpl();
    return controlNode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StartNode createStartNode()
  {
    StartNodeImpl startNode = new StartNodeImpl();
    return startNode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Event createEvent()
  {
    EventImpl event = new EventImpl();
    return event;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Transition createTransition()
  {
    TransitionImpl transition = new TransitionImpl();
    return transition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StoryPatternNode createStoryPatternNode()
  {
    StoryPatternNodeImpl storyPatternNode = new StoryPatternNodeImpl();
    return storyPatternNode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RoleNode createRoleNode()
  {
    RoleNodeImpl roleNode = new RoleNodeImpl();
    return roleNode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RewriteRoleNode createRewriteRoleNode()
  {
    RewriteRoleNodeImpl rewriteRoleNode = new RewriteRoleNodeImpl();
    return rewriteRoleNode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RemoveRoleNode createRemoveRoleNode()
  {
    RemoveRoleNodeImpl removeRoleNode = new RemoveRoleNodeImpl();
    return removeRoleNode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RenewRoleNode createRenewRoleNode()
  {
    RenewRoleNodeImpl renewRoleNode = new RenewRoleNodeImpl();
    return renewRoleNode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AddRoleNode createAddRoleNode()
  {
    AddRoleNodeImpl addRoleNode = new AddRoleNodeImpl();
    return addRoleNode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ConditionRoleNode createConditionRoleNode()
  {
    ConditionRoleNodeImpl conditionRoleNode = new ConditionRoleNodeImpl();
    return conditionRoleNode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProhibitedRoleNode createProhibitedRoleNode()
  {
    ProhibitedRoleNodeImpl prohibitedRoleNode = new ProhibitedRoleNodeImpl();
    return prohibitedRoleNode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PlayRoleNode createPlayRoleNode()
  {
    PlayRoleNodeImpl playRoleNode = new PlayRoleNodeImpl();
    return playRoleNode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DslPackage getDslPackage()
  {
    return (DslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static DslPackage getPackage()
  {
    return DslPackage.eINSTANCE;
  }

} //DslFactoryImpl
