/**
 * generated by Xtext 2.9.1
 */
package de.larsschuetze.storyboard.dsl.impl;

import de.larsschuetze.storyboard.dsl.DslPackage;
import de.larsschuetze.storyboard.dsl.RoleNode;
import de.larsschuetze.storyboard.dsl.StoryPatternNode;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Story Pattern Node</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link de.larsschuetze.storyboard.dsl.impl.StoryPatternNodeImpl#getClassName <em>Class Name</em>}</li>
 *   <li>{@link de.larsschuetze.storyboard.dsl.impl.StoryPatternNodeImpl#getRoleReconfigurations <em>Role Reconfigurations</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class StoryPatternNodeImpl extends NodeImpl implements StoryPatternNode
{
  /**
   * The default value of the '{@link #getClassName() <em>Class Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClassName()
   * @generated
   * @ordered
   */
  protected static final String CLASS_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getClassName() <em>Class Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClassName()
   * @generated
   * @ordered
   */
  protected String className = CLASS_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getRoleReconfigurations() <em>Role Reconfigurations</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRoleReconfigurations()
   * @generated
   * @ordered
   */
  protected EList<RoleNode> roleReconfigurations;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StoryPatternNodeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.STORY_PATTERN_NODE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getClassName()
  {
    return className;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setClassName(String newClassName)
  {
    String oldClassName = className;
    className = newClassName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.STORY_PATTERN_NODE__CLASS_NAME, oldClassName, className));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<RoleNode> getRoleReconfigurations()
  {
    if (roleReconfigurations == null)
    {
      roleReconfigurations = new EObjectContainmentEList<RoleNode>(RoleNode.class, this, DslPackage.STORY_PATTERN_NODE__ROLE_RECONFIGURATIONS);
    }
    return roleReconfigurations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DslPackage.STORY_PATTERN_NODE__ROLE_RECONFIGURATIONS:
        return ((InternalEList<?>)getRoleReconfigurations()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.STORY_PATTERN_NODE__CLASS_NAME:
        return getClassName();
      case DslPackage.STORY_PATTERN_NODE__ROLE_RECONFIGURATIONS:
        return getRoleReconfigurations();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.STORY_PATTERN_NODE__CLASS_NAME:
        setClassName((String)newValue);
        return;
      case DslPackage.STORY_PATTERN_NODE__ROLE_RECONFIGURATIONS:
        getRoleReconfigurations().clear();
        getRoleReconfigurations().addAll((Collection<? extends RoleNode>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.STORY_PATTERN_NODE__CLASS_NAME:
        setClassName(CLASS_NAME_EDEFAULT);
        return;
      case DslPackage.STORY_PATTERN_NODE__ROLE_RECONFIGURATIONS:
        getRoleReconfigurations().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.STORY_PATTERN_NODE__CLASS_NAME:
        return CLASS_NAME_EDEFAULT == null ? className != null : !CLASS_NAME_EDEFAULT.equals(className);
      case DslPackage.STORY_PATTERN_NODE__ROLE_RECONFIGURATIONS:
        return roleReconfigurations != null && !roleReconfigurations.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (className: ");
    result.append(className);
    result.append(')');
    return result.toString();
  }

} //StoryPatternNodeImpl
