/**
 * generated by Xtext 2.9.1
 */
package de.larsschuetze.storyboard.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Control Node</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.larsschuetze.storyboard.dsl.DslPackage#getControlNode()
 * @model
 * @generated
 */
public interface ControlNode extends Node
{
} // ControlNode
