/**
 * generated by Xtext 2.9.1
 */
package de.larsschuetze.storyboard.dsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.larsschuetze.storyboard.dsl.DslFactory
 * @model kind="package"
 * @generated
 */
public interface DslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.larsschuetze.de/storyboard/Dsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DslPackage eINSTANCE = de.larsschuetze.storyboard.dsl.impl.DslPackageImpl.init();

  /**
   * The meta object id for the '{@link de.larsschuetze.storyboard.dsl.impl.StoryboardImpl <em>Storyboard</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.larsschuetze.storyboard.dsl.impl.StoryboardImpl
   * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getStoryboard()
   * @generated
   */
  int STORYBOARD = 0;

  /**
   * The feature id for the '<em><b>Imported Events</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORYBOARD__IMPORTED_EVENTS = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORYBOARD__NAME = 1;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORYBOARD__ELEMENTS = 2;

  /**
   * The number of structural features of the '<em>Storyboard</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORYBOARD_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link de.larsschuetze.storyboard.dsl.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.larsschuetze.storyboard.dsl.impl.AbstractElementImpl
   * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.larsschuetze.storyboard.dsl.impl.NodeImpl <em>Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.larsschuetze.storyboard.dsl.impl.NodeImpl
   * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getNode()
   * @generated
   */
  int NODE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.larsschuetze.storyboard.dsl.impl.ControlNodeImpl <em>Control Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.larsschuetze.storyboard.dsl.impl.ControlNodeImpl
   * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getControlNode()
   * @generated
   */
  int CONTROL_NODE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL_NODE__NAME = NODE__NAME;

  /**
   * The number of structural features of the '<em>Control Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL_NODE_FEATURE_COUNT = NODE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.larsschuetze.storyboard.dsl.impl.StartNodeImpl <em>Start Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.larsschuetze.storyboard.dsl.impl.StartNodeImpl
   * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getStartNode()
   * @generated
   */
  int START_NODE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_NODE__NAME = CONTROL_NODE__NAME;

  /**
   * The number of structural features of the '<em>Start Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_NODE_FEATURE_COUNT = CONTROL_NODE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.larsschuetze.storyboard.dsl.impl.EndNodeImpl <em>End Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.larsschuetze.storyboard.dsl.impl.EndNodeImpl
   * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getEndNode()
   * @generated
   */
  int END_NODE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_NODE__NAME = CONTROL_NODE__NAME;

  /**
   * The number of structural features of the '<em>End Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_NODE_FEATURE_COUNT = CONTROL_NODE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.larsschuetze.storyboard.dsl.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.larsschuetze.storyboard.dsl.impl.EventImpl
   * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 6;

  /**
   * The feature id for the '<em><b>Event Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__EVENT_TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = 1;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.larsschuetze.storyboard.dsl.impl.TransitionImpl <em>Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.larsschuetze.storyboard.dsl.impl.TransitionImpl
   * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getTransition()
   * @generated
   */
  int TRANSITION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__EVENT = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Guard</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__GUARD = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__SOURCE = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Source Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__SOURCE_PORT = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__TARGET = ABSTRACT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link de.larsschuetze.storyboard.dsl.impl.GuardImpl <em>Guard</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.larsschuetze.storyboard.dsl.impl.GuardImpl
   * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getGuard()
   * @generated
   */
  int GUARD = 8;

  /**
   * The feature id for the '<em><b>Guard</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUARD__GUARD = 0;

  /**
   * The number of structural features of the '<em>Guard</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUARD_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.larsschuetze.storyboard.dsl.impl.StoryPatternNodeImpl <em>Story Pattern Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.larsschuetze.storyboard.dsl.impl.StoryPatternNodeImpl
   * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getStoryPatternNode()
   * @generated
   */
  int STORY_PATTERN_NODE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY_PATTERN_NODE__NAME = NODE__NAME;

  /**
   * The feature id for the '<em><b>Class Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY_PATTERN_NODE__CLASS_NAME = NODE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Role Reconfigurations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY_PATTERN_NODE__ROLE_RECONFIGURATIONS = NODE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Story Pattern Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY_PATTERN_NODE_FEATURE_COUNT = NODE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link de.larsschuetze.storyboard.dsl.impl.RoleNodeImpl <em>Role Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.larsschuetze.storyboard.dsl.impl.RoleNodeImpl
   * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getRoleNode()
   * @generated
   */
  int ROLE_NODE = 10;

  /**
   * The feature id for the '<em><b>Compartment Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_NODE__COMPARTMENT_NAME = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_NODE__NAME = 1;

  /**
   * The number of structural features of the '<em>Role Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_NODE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.larsschuetze.storyboard.dsl.impl.RewriteRoleNodeImpl <em>Rewrite Role Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.larsschuetze.storyboard.dsl.impl.RewriteRoleNodeImpl
   * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getRewriteRoleNode()
   * @generated
   */
  int REWRITE_ROLE_NODE = 11;

  /**
   * The feature id for the '<em><b>Compartment Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REWRITE_ROLE_NODE__COMPARTMENT_NAME = ROLE_NODE__COMPARTMENT_NAME;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REWRITE_ROLE_NODE__NAME = ROLE_NODE__NAME;

  /**
   * The number of structural features of the '<em>Rewrite Role Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REWRITE_ROLE_NODE_FEATURE_COUNT = ROLE_NODE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.larsschuetze.storyboard.dsl.impl.RemoveRoleNodeImpl <em>Remove Role Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.larsschuetze.storyboard.dsl.impl.RemoveRoleNodeImpl
   * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getRemoveRoleNode()
   * @generated
   */
  int REMOVE_ROLE_NODE = 12;

  /**
   * The feature id for the '<em><b>Compartment Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE_ROLE_NODE__COMPARTMENT_NAME = REWRITE_ROLE_NODE__COMPARTMENT_NAME;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE_ROLE_NODE__NAME = REWRITE_ROLE_NODE__NAME;

  /**
   * The number of structural features of the '<em>Remove Role Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE_ROLE_NODE_FEATURE_COUNT = REWRITE_ROLE_NODE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.larsschuetze.storyboard.dsl.impl.RenewRoleNodeImpl <em>Renew Role Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.larsschuetze.storyboard.dsl.impl.RenewRoleNodeImpl
   * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getRenewRoleNode()
   * @generated
   */
  int RENEW_ROLE_NODE = 13;

  /**
   * The feature id for the '<em><b>Compartment Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENEW_ROLE_NODE__COMPARTMENT_NAME = REWRITE_ROLE_NODE__COMPARTMENT_NAME;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENEW_ROLE_NODE__NAME = REWRITE_ROLE_NODE__NAME;

  /**
   * The number of structural features of the '<em>Renew Role Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENEW_ROLE_NODE_FEATURE_COUNT = REWRITE_ROLE_NODE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.larsschuetze.storyboard.dsl.impl.AddRoleNodeImpl <em>Add Role Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.larsschuetze.storyboard.dsl.impl.AddRoleNodeImpl
   * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getAddRoleNode()
   * @generated
   */
  int ADD_ROLE_NODE = 14;

  /**
   * The feature id for the '<em><b>Compartment Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_ROLE_NODE__COMPARTMENT_NAME = REWRITE_ROLE_NODE__COMPARTMENT_NAME;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_ROLE_NODE__NAME = REWRITE_ROLE_NODE__NAME;

  /**
   * The number of structural features of the '<em>Add Role Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_ROLE_NODE_FEATURE_COUNT = REWRITE_ROLE_NODE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.larsschuetze.storyboard.dsl.impl.ConditionRoleNodeImpl <em>Condition Role Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.larsschuetze.storyboard.dsl.impl.ConditionRoleNodeImpl
   * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getConditionRoleNode()
   * @generated
   */
  int CONDITION_ROLE_NODE = 15;

  /**
   * The feature id for the '<em><b>Compartment Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_ROLE_NODE__COMPARTMENT_NAME = ROLE_NODE__COMPARTMENT_NAME;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_ROLE_NODE__NAME = ROLE_NODE__NAME;

  /**
   * The number of structural features of the '<em>Condition Role Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_ROLE_NODE_FEATURE_COUNT = ROLE_NODE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.larsschuetze.storyboard.dsl.impl.ProhibitedRoleNodeImpl <em>Prohibited Role Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.larsschuetze.storyboard.dsl.impl.ProhibitedRoleNodeImpl
   * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getProhibitedRoleNode()
   * @generated
   */
  int PROHIBITED_ROLE_NODE = 16;

  /**
   * The feature id for the '<em><b>Compartment Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROHIBITED_ROLE_NODE__COMPARTMENT_NAME = CONDITION_ROLE_NODE__COMPARTMENT_NAME;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROHIBITED_ROLE_NODE__NAME = CONDITION_ROLE_NODE__NAME;

  /**
   * The number of structural features of the '<em>Prohibited Role Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROHIBITED_ROLE_NODE_FEATURE_COUNT = CONDITION_ROLE_NODE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.larsschuetze.storyboard.dsl.impl.PlayRoleNodeImpl <em>Play Role Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.larsschuetze.storyboard.dsl.impl.PlayRoleNodeImpl
   * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getPlayRoleNode()
   * @generated
   */
  int PLAY_ROLE_NODE = 17;

  /**
   * The feature id for the '<em><b>Compartment Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLAY_ROLE_NODE__COMPARTMENT_NAME = CONDITION_ROLE_NODE__COMPARTMENT_NAME;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLAY_ROLE_NODE__NAME = CONDITION_ROLE_NODE__NAME;

  /**
   * The number of structural features of the '<em>Play Role Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLAY_ROLE_NODE_FEATURE_COUNT = CONDITION_ROLE_NODE_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link de.larsschuetze.storyboard.dsl.Storyboard <em>Storyboard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Storyboard</em>'.
   * @see de.larsschuetze.storyboard.dsl.Storyboard
   * @generated
   */
  EClass getStoryboard();

  /**
   * Returns the meta object for the containment reference list '{@link de.larsschuetze.storyboard.dsl.Storyboard#getImportedEvents <em>Imported Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imported Events</em>'.
   * @see de.larsschuetze.storyboard.dsl.Storyboard#getImportedEvents()
   * @see #getStoryboard()
   * @generated
   */
  EReference getStoryboard_ImportedEvents();

  /**
   * Returns the meta object for the attribute '{@link de.larsschuetze.storyboard.dsl.Storyboard#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.larsschuetze.storyboard.dsl.Storyboard#getName()
   * @see #getStoryboard()
   * @generated
   */
  EAttribute getStoryboard_Name();

  /**
   * Returns the meta object for the containment reference list '{@link de.larsschuetze.storyboard.dsl.Storyboard#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see de.larsschuetze.storyboard.dsl.Storyboard#getElements()
   * @see #getStoryboard()
   * @generated
   */
  EReference getStoryboard_Elements();

  /**
   * Returns the meta object for class '{@link de.larsschuetze.storyboard.dsl.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see de.larsschuetze.storyboard.dsl.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for the attribute '{@link de.larsschuetze.storyboard.dsl.AbstractElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.larsschuetze.storyboard.dsl.AbstractElement#getName()
   * @see #getAbstractElement()
   * @generated
   */
  EAttribute getAbstractElement_Name();

  /**
   * Returns the meta object for class '{@link de.larsschuetze.storyboard.dsl.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node</em>'.
   * @see de.larsschuetze.storyboard.dsl.Node
   * @generated
   */
  EClass getNode();

  /**
   * Returns the meta object for class '{@link de.larsschuetze.storyboard.dsl.ControlNode <em>Control Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Control Node</em>'.
   * @see de.larsschuetze.storyboard.dsl.ControlNode
   * @generated
   */
  EClass getControlNode();

  /**
   * Returns the meta object for class '{@link de.larsschuetze.storyboard.dsl.StartNode <em>Start Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Start Node</em>'.
   * @see de.larsschuetze.storyboard.dsl.StartNode
   * @generated
   */
  EClass getStartNode();

  /**
   * Returns the meta object for class '{@link de.larsschuetze.storyboard.dsl.EndNode <em>End Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>End Node</em>'.
   * @see de.larsschuetze.storyboard.dsl.EndNode
   * @generated
   */
  EClass getEndNode();

  /**
   * Returns the meta object for class '{@link de.larsschuetze.storyboard.dsl.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see de.larsschuetze.storyboard.dsl.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the containment reference '{@link de.larsschuetze.storyboard.dsl.Event#getEventType <em>Event Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Event Type</em>'.
   * @see de.larsschuetze.storyboard.dsl.Event#getEventType()
   * @see #getEvent()
   * @generated
   */
  EReference getEvent_EventType();

  /**
   * Returns the meta object for the attribute '{@link de.larsschuetze.storyboard.dsl.Event#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.larsschuetze.storyboard.dsl.Event#getName()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Name();

  /**
   * Returns the meta object for class '{@link de.larsschuetze.storyboard.dsl.Transition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition</em>'.
   * @see de.larsschuetze.storyboard.dsl.Transition
   * @generated
   */
  EClass getTransition();

  /**
   * Returns the meta object for the reference '{@link de.larsschuetze.storyboard.dsl.Transition#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Event</em>'.
   * @see de.larsschuetze.storyboard.dsl.Transition#getEvent()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Event();

  /**
   * Returns the meta object for the containment reference '{@link de.larsschuetze.storyboard.dsl.Transition#getGuard <em>Guard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Guard</em>'.
   * @see de.larsschuetze.storyboard.dsl.Transition#getGuard()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Guard();

  /**
   * Returns the meta object for the reference '{@link de.larsschuetze.storyboard.dsl.Transition#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source</em>'.
   * @see de.larsschuetze.storyboard.dsl.Transition#getSource()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Source();

  /**
   * Returns the meta object for the attribute '{@link de.larsschuetze.storyboard.dsl.Transition#getSourcePort <em>Source Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source Port</em>'.
   * @see de.larsschuetze.storyboard.dsl.Transition#getSourcePort()
   * @see #getTransition()
   * @generated
   */
  EAttribute getTransition_SourcePort();

  /**
   * Returns the meta object for the reference '{@link de.larsschuetze.storyboard.dsl.Transition#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see de.larsschuetze.storyboard.dsl.Transition#getTarget()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Target();

  /**
   * Returns the meta object for class '{@link de.larsschuetze.storyboard.dsl.Guard <em>Guard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Guard</em>'.
   * @see de.larsschuetze.storyboard.dsl.Guard
   * @generated
   */
  EClass getGuard();

  /**
   * Returns the meta object for the attribute '{@link de.larsschuetze.storyboard.dsl.Guard#getGuard <em>Guard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Guard</em>'.
   * @see de.larsschuetze.storyboard.dsl.Guard#getGuard()
   * @see #getGuard()
   * @generated
   */
  EAttribute getGuard_Guard();

  /**
   * Returns the meta object for class '{@link de.larsschuetze.storyboard.dsl.StoryPatternNode <em>Story Pattern Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Story Pattern Node</em>'.
   * @see de.larsschuetze.storyboard.dsl.StoryPatternNode
   * @generated
   */
  EClass getStoryPatternNode();

  /**
   * Returns the meta object for the attribute '{@link de.larsschuetze.storyboard.dsl.StoryPatternNode#getClassName <em>Class Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Class Name</em>'.
   * @see de.larsschuetze.storyboard.dsl.StoryPatternNode#getClassName()
   * @see #getStoryPatternNode()
   * @generated
   */
  EAttribute getStoryPatternNode_ClassName();

  /**
   * Returns the meta object for the containment reference list '{@link de.larsschuetze.storyboard.dsl.StoryPatternNode#getRoleReconfigurations <em>Role Reconfigurations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Role Reconfigurations</em>'.
   * @see de.larsschuetze.storyboard.dsl.StoryPatternNode#getRoleReconfigurations()
   * @see #getStoryPatternNode()
   * @generated
   */
  EReference getStoryPatternNode_RoleReconfigurations();

  /**
   * Returns the meta object for class '{@link de.larsschuetze.storyboard.dsl.RoleNode <em>Role Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Role Node</em>'.
   * @see de.larsschuetze.storyboard.dsl.RoleNode
   * @generated
   */
  EClass getRoleNode();

  /**
   * Returns the meta object for the attribute '{@link de.larsschuetze.storyboard.dsl.RoleNode#getCompartmentName <em>Compartment Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Compartment Name</em>'.
   * @see de.larsschuetze.storyboard.dsl.RoleNode#getCompartmentName()
   * @see #getRoleNode()
   * @generated
   */
  EAttribute getRoleNode_CompartmentName();

  /**
   * Returns the meta object for the attribute '{@link de.larsschuetze.storyboard.dsl.RoleNode#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.larsschuetze.storyboard.dsl.RoleNode#getName()
   * @see #getRoleNode()
   * @generated
   */
  EAttribute getRoleNode_Name();

  /**
   * Returns the meta object for class '{@link de.larsschuetze.storyboard.dsl.RewriteRoleNode <em>Rewrite Role Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rewrite Role Node</em>'.
   * @see de.larsschuetze.storyboard.dsl.RewriteRoleNode
   * @generated
   */
  EClass getRewriteRoleNode();

  /**
   * Returns the meta object for class '{@link de.larsschuetze.storyboard.dsl.RemoveRoleNode <em>Remove Role Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Remove Role Node</em>'.
   * @see de.larsschuetze.storyboard.dsl.RemoveRoleNode
   * @generated
   */
  EClass getRemoveRoleNode();

  /**
   * Returns the meta object for class '{@link de.larsschuetze.storyboard.dsl.RenewRoleNode <em>Renew Role Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Renew Role Node</em>'.
   * @see de.larsschuetze.storyboard.dsl.RenewRoleNode
   * @generated
   */
  EClass getRenewRoleNode();

  /**
   * Returns the meta object for class '{@link de.larsschuetze.storyboard.dsl.AddRoleNode <em>Add Role Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add Role Node</em>'.
   * @see de.larsschuetze.storyboard.dsl.AddRoleNode
   * @generated
   */
  EClass getAddRoleNode();

  /**
   * Returns the meta object for class '{@link de.larsschuetze.storyboard.dsl.ConditionRoleNode <em>Condition Role Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition Role Node</em>'.
   * @see de.larsschuetze.storyboard.dsl.ConditionRoleNode
   * @generated
   */
  EClass getConditionRoleNode();

  /**
   * Returns the meta object for class '{@link de.larsschuetze.storyboard.dsl.ProhibitedRoleNode <em>Prohibited Role Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prohibited Role Node</em>'.
   * @see de.larsschuetze.storyboard.dsl.ProhibitedRoleNode
   * @generated
   */
  EClass getProhibitedRoleNode();

  /**
   * Returns the meta object for class '{@link de.larsschuetze.storyboard.dsl.PlayRoleNode <em>Play Role Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Play Role Node</em>'.
   * @see de.larsschuetze.storyboard.dsl.PlayRoleNode
   * @generated
   */
  EClass getPlayRoleNode();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DslFactory getDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.larsschuetze.storyboard.dsl.impl.StoryboardImpl <em>Storyboard</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.larsschuetze.storyboard.dsl.impl.StoryboardImpl
     * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getStoryboard()
     * @generated
     */
    EClass STORYBOARD = eINSTANCE.getStoryboard();

    /**
     * The meta object literal for the '<em><b>Imported Events</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORYBOARD__IMPORTED_EVENTS = eINSTANCE.getStoryboard_ImportedEvents();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORYBOARD__NAME = eINSTANCE.getStoryboard_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORYBOARD__ELEMENTS = eINSTANCE.getStoryboard_Elements();

    /**
     * The meta object literal for the '{@link de.larsschuetze.storyboard.dsl.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.larsschuetze.storyboard.dsl.impl.AbstractElementImpl
     * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSTRACT_ELEMENT__NAME = eINSTANCE.getAbstractElement_Name();

    /**
     * The meta object literal for the '{@link de.larsschuetze.storyboard.dsl.impl.NodeImpl <em>Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.larsschuetze.storyboard.dsl.impl.NodeImpl
     * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getNode()
     * @generated
     */
    EClass NODE = eINSTANCE.getNode();

    /**
     * The meta object literal for the '{@link de.larsschuetze.storyboard.dsl.impl.ControlNodeImpl <em>Control Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.larsschuetze.storyboard.dsl.impl.ControlNodeImpl
     * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getControlNode()
     * @generated
     */
    EClass CONTROL_NODE = eINSTANCE.getControlNode();

    /**
     * The meta object literal for the '{@link de.larsschuetze.storyboard.dsl.impl.StartNodeImpl <em>Start Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.larsschuetze.storyboard.dsl.impl.StartNodeImpl
     * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getStartNode()
     * @generated
     */
    EClass START_NODE = eINSTANCE.getStartNode();

    /**
     * The meta object literal for the '{@link de.larsschuetze.storyboard.dsl.impl.EndNodeImpl <em>End Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.larsschuetze.storyboard.dsl.impl.EndNodeImpl
     * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getEndNode()
     * @generated
     */
    EClass END_NODE = eINSTANCE.getEndNode();

    /**
     * The meta object literal for the '{@link de.larsschuetze.storyboard.dsl.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.larsschuetze.storyboard.dsl.impl.EventImpl
     * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Event Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT__EVENT_TYPE = eINSTANCE.getEvent_EventType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEvent_Name();

    /**
     * The meta object literal for the '{@link de.larsschuetze.storyboard.dsl.impl.TransitionImpl <em>Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.larsschuetze.storyboard.dsl.impl.TransitionImpl
     * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getTransition()
     * @generated
     */
    EClass TRANSITION = eINSTANCE.getTransition();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__EVENT = eINSTANCE.getTransition_Event();

    /**
     * The meta object literal for the '<em><b>Guard</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__GUARD = eINSTANCE.getTransition_Guard();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__SOURCE = eINSTANCE.getTransition_Source();

    /**
     * The meta object literal for the '<em><b>Source Port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION__SOURCE_PORT = eINSTANCE.getTransition_SourcePort();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__TARGET = eINSTANCE.getTransition_Target();

    /**
     * The meta object literal for the '{@link de.larsschuetze.storyboard.dsl.impl.GuardImpl <em>Guard</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.larsschuetze.storyboard.dsl.impl.GuardImpl
     * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getGuard()
     * @generated
     */
    EClass GUARD = eINSTANCE.getGuard();

    /**
     * The meta object literal for the '<em><b>Guard</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GUARD__GUARD = eINSTANCE.getGuard_Guard();

    /**
     * The meta object literal for the '{@link de.larsschuetze.storyboard.dsl.impl.StoryPatternNodeImpl <em>Story Pattern Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.larsschuetze.storyboard.dsl.impl.StoryPatternNodeImpl
     * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getStoryPatternNode()
     * @generated
     */
    EClass STORY_PATTERN_NODE = eINSTANCE.getStoryPatternNode();

    /**
     * The meta object literal for the '<em><b>Class Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORY_PATTERN_NODE__CLASS_NAME = eINSTANCE.getStoryPatternNode_ClassName();

    /**
     * The meta object literal for the '<em><b>Role Reconfigurations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORY_PATTERN_NODE__ROLE_RECONFIGURATIONS = eINSTANCE.getStoryPatternNode_RoleReconfigurations();

    /**
     * The meta object literal for the '{@link de.larsschuetze.storyboard.dsl.impl.RoleNodeImpl <em>Role Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.larsschuetze.storyboard.dsl.impl.RoleNodeImpl
     * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getRoleNode()
     * @generated
     */
    EClass ROLE_NODE = eINSTANCE.getRoleNode();

    /**
     * The meta object literal for the '<em><b>Compartment Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROLE_NODE__COMPARTMENT_NAME = eINSTANCE.getRoleNode_CompartmentName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROLE_NODE__NAME = eINSTANCE.getRoleNode_Name();

    /**
     * The meta object literal for the '{@link de.larsschuetze.storyboard.dsl.impl.RewriteRoleNodeImpl <em>Rewrite Role Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.larsschuetze.storyboard.dsl.impl.RewriteRoleNodeImpl
     * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getRewriteRoleNode()
     * @generated
     */
    EClass REWRITE_ROLE_NODE = eINSTANCE.getRewriteRoleNode();

    /**
     * The meta object literal for the '{@link de.larsschuetze.storyboard.dsl.impl.RemoveRoleNodeImpl <em>Remove Role Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.larsschuetze.storyboard.dsl.impl.RemoveRoleNodeImpl
     * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getRemoveRoleNode()
     * @generated
     */
    EClass REMOVE_ROLE_NODE = eINSTANCE.getRemoveRoleNode();

    /**
     * The meta object literal for the '{@link de.larsschuetze.storyboard.dsl.impl.RenewRoleNodeImpl <em>Renew Role Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.larsschuetze.storyboard.dsl.impl.RenewRoleNodeImpl
     * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getRenewRoleNode()
     * @generated
     */
    EClass RENEW_ROLE_NODE = eINSTANCE.getRenewRoleNode();

    /**
     * The meta object literal for the '{@link de.larsschuetze.storyboard.dsl.impl.AddRoleNodeImpl <em>Add Role Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.larsschuetze.storyboard.dsl.impl.AddRoleNodeImpl
     * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getAddRoleNode()
     * @generated
     */
    EClass ADD_ROLE_NODE = eINSTANCE.getAddRoleNode();

    /**
     * The meta object literal for the '{@link de.larsschuetze.storyboard.dsl.impl.ConditionRoleNodeImpl <em>Condition Role Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.larsschuetze.storyboard.dsl.impl.ConditionRoleNodeImpl
     * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getConditionRoleNode()
     * @generated
     */
    EClass CONDITION_ROLE_NODE = eINSTANCE.getConditionRoleNode();

    /**
     * The meta object literal for the '{@link de.larsschuetze.storyboard.dsl.impl.ProhibitedRoleNodeImpl <em>Prohibited Role Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.larsschuetze.storyboard.dsl.impl.ProhibitedRoleNodeImpl
     * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getProhibitedRoleNode()
     * @generated
     */
    EClass PROHIBITED_ROLE_NODE = eINSTANCE.getProhibitedRoleNode();

    /**
     * The meta object literal for the '{@link de.larsschuetze.storyboard.dsl.impl.PlayRoleNodeImpl <em>Play Role Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.larsschuetze.storyboard.dsl.impl.PlayRoleNodeImpl
     * @see de.larsschuetze.storyboard.dsl.impl.DslPackageImpl#getPlayRoleNode()
     * @generated
     */
    EClass PLAY_ROLE_NODE = eINSTANCE.getPlayRoleNode();

  }

} //DslPackage
