/**
 * generated by Xtext 2.9.1
 */
package de.larsschuetze.storyboard.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prohibited Role Node</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.larsschuetze.storyboard.dsl.DslPackage#getProhibitedRoleNode()
 * @model
 * @generated
 */
public interface ProhibitedRoleNode extends ConditionRoleNode
{
} // ProhibitedRoleNode
