/**
 * generated by Xtext 2.9.1
 */
package de.larsschuetze.storyboard.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Renew Role Node</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.larsschuetze.storyboard.dsl.DslPackage#getRenewRoleNode()
 * @model
 * @generated
 */
public interface RenewRoleNode extends RewriteRoleNode
{
} // RenewRoleNode
