/**
 * generated by Xtext 2.9.1
 */
package de.larsschuetze.storyboard.dsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Story Pattern Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link de.larsschuetze.storyboard.dsl.StoryPatternNode#getName <em>Name</em>}</li>
 *   <li>{@link de.larsschuetze.storyboard.dsl.StoryPatternNode#getClassName <em>Class Name</em>}</li>
 *   <li>{@link de.larsschuetze.storyboard.dsl.StoryPatternNode#getRoleReconfigurations <em>Role Reconfigurations</em>}</li>
 * </ul>
 * </p>
 *
 * @see de.larsschuetze.storyboard.dsl.DslPackage#getStoryPatternNode()
 * @model
 * @generated
 */
public interface StoryPatternNode extends Node
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.larsschuetze.storyboard.dsl.DslPackage#getStoryPatternNode_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.larsschuetze.storyboard.dsl.StoryPatternNode#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Class Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Class Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class Name</em>' attribute.
   * @see #setClassName(String)
   * @see de.larsschuetze.storyboard.dsl.DslPackage#getStoryPatternNode_ClassName()
   * @model
   * @generated
   */
  String getClassName();

  /**
   * Sets the value of the '{@link de.larsschuetze.storyboard.dsl.StoryPatternNode#getClassName <em>Class Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class Name</em>' attribute.
   * @see #getClassName()
   * @generated
   */
  void setClassName(String value);

  /**
   * Returns the value of the '<em><b>Role Reconfigurations</b></em>' containment reference list.
   * The list contents are of type {@link de.larsschuetze.storyboard.dsl.RoleNode}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Role Reconfigurations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role Reconfigurations</em>' containment reference list.
   * @see de.larsschuetze.storyboard.dsl.DslPackage#getStoryPatternNode_RoleReconfigurations()
   * @model containment="true"
   * @generated
   */
  EList<RoleNode> getRoleReconfigurations();

} // StoryPatternNode
