/**
 * generated by Xtext 2.9.1
 */
package de.larsschuetze.storyboard.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Storyboard</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link de.larsschuetze.storyboard.dsl.Storyboard#getImportedEvents <em>Imported Events</em>}</li>
 *   <li>{@link de.larsschuetze.storyboard.dsl.Storyboard#getName <em>Name</em>}</li>
 *   <li>{@link de.larsschuetze.storyboard.dsl.Storyboard#getElements <em>Elements</em>}</li>
 * </ul>
 * </p>
 *
 * @see de.larsschuetze.storyboard.dsl.DslPackage#getStoryboard()
 * @model
 * @generated
 */
public interface Storyboard extends EObject
{
  /**
   * Returns the value of the '<em><b>Imported Events</b></em>' containment reference list.
   * The list contents are of type {@link de.larsschuetze.storyboard.dsl.Event}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Imported Events</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imported Events</em>' containment reference list.
   * @see de.larsschuetze.storyboard.dsl.DslPackage#getStoryboard_ImportedEvents()
   * @model containment="true"
   * @generated
   */
  EList<Event> getImportedEvents();

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.larsschuetze.storyboard.dsl.DslPackage#getStoryboard_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.larsschuetze.storyboard.dsl.Storyboard#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link de.larsschuetze.storyboard.dsl.AbstractElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see de.larsschuetze.storyboard.dsl.DslPackage#getStoryboard_Elements()
   * @model containment="true"
   * @generated
   */
  EList<AbstractElement> getElements();

} // Storyboard
