/*
 * generated by Xtext 2.9.1
 */
package de.larsschuetze.storyboard.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/larsschuetze/storyboard/parser/antlr/internal/InternalDsl.tokens");
	}
}
