/*
 * generated by Xtext 2.9.1
 */
package de.larsschuetze.storyboard

import org.eclipse.xtext.generator.IGenerator
import de.larsschuetze.storyboard.generator.DslGenerator

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DslRuntimeModule extends AbstractDslRuntimeModule {

	override Class<? extends IGenerator> bindIGenerator() {
		return DslGenerator
	}
}
