/*
 * generated by Xtext 2.9.1
 */
package de.larsschuetze.storyboard.ui.tests;

import com.google.inject.Injector;
import de.larsschuetze.storyboard.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("de.larsschuetze.storyboard.Dsl");
	}

}
