/*
 * generated by Xtext 2.9.1
 */
package de.larsschuetze.storyboard.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractDslScopeProvider extends XbaseBatchScopeProvider {
}
